RestaurantMVC/RestaurantMVC/Entities/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RestaurantMVC.Entities
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        [StringLength(10, MinimumLength =4)]
        [Required]
        public string Name { get; set; }

        [Column(TypeName = "money")]
        public decimal Price { get; set; }
    }
}     

RestaurantMVC/RestaurantMVC/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.Models;
using RestaurantMVC.Services;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace RestaurantMVC.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        private readonly IAccountService accountService;

        public ProductController(IProductService productService, IAccountService accountService)
        {
            this.productService = productService;
            this.accountService = accountService;
        }

        // GET: ProductController
        [HttpGet()]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create([FromForm] ProductDto productDto)
        {
            await productService.Create(productDto, User);
            return View("Index");
        }

        [HttpGet("create")]
        public IActionResult CreateForm()
        {
            return View();
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit([FromForm] ProductDto productDto)
        {
            await productService.Edit(productDto, User);
            return View("Index");
        }

        [HttpPost("delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            await productService.Delete(id, User);
            return View("Index");
        }

        [HttpGet("get/{id}")]
        public async Task<IActionResult> Get([FromRoute]int id)
        {
            ProductDto productDto =  await productService.Get(id);
            return View(productDto);
        }
        [HttpGet("get")]
        public async Task<IActionResult> Get()
        {
            List<ProductDto> producDtos = await productService.Get();
            ViewBag.RoleId = accountService.GetUser(User).RoleId;

            return View(producDtos);
        }
        [HttpGet("search/{searchPhrase}")]
        public async Task<IActionResult> Search(string searchPhrase)
        {
            List<ProductDto> producDtos = await productService.Search(searchPhrase);
            return View(producDtos);
        }

    }
}

RestaurantMVC/RestaurantMVC/Views/Product/CreateForm.cshtml
@model RestaurantMVC.Entities.Product

@{
    ViewData["Title"] = "Create product";
}

<h1>Create product</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Get">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RestaurantMVC/RestaurantMVC/Views/Product/Get.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ }


@model List<ProductDto>;
<!--
foreach(var dto in Model)
{
    <div>

        dto.Name

        using( Html.BeginForm("Delete", "Product", new { id = dto.Id }))
        {
            <input type="submit" value="delete"/>
        }
    </div>
}
-->
<table class="content-wrapper table table-dark">
    <tr>
        <th scope="col">
            @Html.DisplayName("Name")
        </th>
        <th scope="col">
            @Html.DisplayName("ID")
        </th>
        <th scope="col">
            @Html.DisplayName("Price")
        </th>
    </tr>
    @foreach (var dto in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => dto.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => dto.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => dto.Price)
            </td>
            <td>

                @if (ViewBag.RoleId == 1)
                {
                    using (Html.BeginForm("Delete", "Product", new { id = dto.Id }))
                    {
                        <input class="btn btn-outline-danger" type="submit" value="Delete Item" />
                    }
                }
            </td>
        </tr>
    }
</table>

RestaurantMVC/RestaurantMVC/Views/Product/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1 style=mx-auto align="center">Position deleted/created succesfully.</h1>
<a class="nav-link text-dark mt-2 col pe-auto  p-10 btn btn-outline-primary" data-mdb-ripple-color="dark" asp-area="" asp-controller="Product" asp-action="Get">Go back to list</a>

RestaurantMVC/RestaurantMVC/Views/Product/ViewUwU.cshtml
@model RestaurantMVC.Models.ProductDto

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    @using (Html.BeginForm("Delete", "Product", FormMethod.Post, new { id = Model.Id }))
    {
        <input type="submit" class="button" value="Delete" />
    }
</div>