RestaurantMVC/RestaurantMVC/Entities/Order.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RestaurantMVC.Entities
{
    public class Order
    {
        public Order()
        {
            Products = new List<OrderProducts>();
        }

        [Key]
        public int Id { get; set; }

        [ForeignKey("User")]
        public int UserId { get; set; }
        public User User { get; set; }

        public virtual ICollection<OrderProducts> Products { get; set; }

        public bool isDone { get; set; }
    }
}

RestaurantMVC/RestaurantMVC/Entities/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RestaurantMVC.Entities
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        [StringLength(10, MinimumLength =4)]
        [Required]
        public string Name { get; set; }

        [Column(TypeName = "money")]
        public decimal Price { get; set; }
    }
}     

RestaurantMVC/RestaurantMVC/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.Models;
using RestaurantMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RestaurantMVC.Entities;

namespace RestaurantMVC.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class OrderController : Controller
    {
        private readonly IProductService productService; 
        private readonly IOrderService orderService;
        public OrderController(IOrderService orderService, IProductService productService)
        {
            this.orderService = orderService;
            this.productService = productService;
        }

        [HttpGet()]
        public async Task<IActionResult> Index()
        {
            //List<OrderDto> orderDtos = await orderService.Get(User);
            return RedirectToAction("Get");
        }
        [HttpPost("create")]
        public async Task<IActionResult> Create()
        {
            OrderDto orderDto = new OrderDto()
            {
                isDone = false, Products = new List<OrderProducts>()
            };
            await orderService.Create(orderDto, User);

            List<OrderDto> orderDtos = await orderService.Get(User);
            return RedirectToAction("Index");
        }

        [HttpPost("delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            await orderService.Delete(id, User);
            return RedirectToAction("Index");
        }

        [HttpGet("get/{id}")]
        public async Task<IActionResult> Get([FromRoute] int id)
        {
            OrderDto orderDto = await orderService.Get(id, User);
            return View(orderDto);
        }
        [HttpGet("get")]
        public async Task<IActionResult> Get()
        {
            List<OrderDto> orderDtos = await orderService.Get(User);
            return View(orderDtos);
        }

        [HttpGet("addproduct/{orderId}")]
        public async Task<IActionResult> AddProduct([FromRoute] int orderId)
        {
            var products = await productService.Get();
            return View("addproduct", products);
        }
        [HttpPost("addproduct/{orderId}/{productId}")]
        public async Task<IActionResult> AddProduct([FromRoute] int orderId, [FromRoute] int productId)
        {
            await orderService.AddProduct(orderId, productId, User);
            return RedirectToAction($"addproduct", new {orderId});
        }

        [HttpGet("products/{orderId}")]
        public async Task<IActionResult> Products([FromRoute] int orderId)
        {
            var productDtos = await orderService.GetProducts(orderId, User);

            return View(productDtos);
        }
    }
}

RestaurantMVC/RestaurantMVC/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.Models;
using RestaurantMVC.Services;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace RestaurantMVC.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        private readonly IAccountService accountService;

        public ProductController(IProductService productService, IAccountService accountService)
        {
            this.productService = productService;
            this.accountService = accountService;
        }

        // GET: ProductController
        [HttpGet()]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create([FromForm] ProductDto productDto)
        {
            await productService.Create(productDto, User);
            return View("Index");
        }

        [HttpGet("create")]
        public IActionResult CreateForm()
        {
            return View();
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit([FromForm] ProductDto productDto)
        {
            await productService.Edit(productDto, User);
            return View("Index");
        }

        [HttpPost("delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            await productService.Delete(id, User);
            return View("Index");
        }

        [HttpGet("get/{id}")]
        public async Task<IActionResult> Get([FromRoute]int id)
        {
            ProductDto productDto =  await productService.Get(id);
            return View(productDto);
        }
        [HttpGet("get")]
        public async Task<IActionResult> Get()
        {
            List<ProductDto> producDtos = await productService.Get();
            ViewBag.RoleId = accountService.GetUser(User).RoleId;

            return View(producDtos);
        }
        [HttpGet("search/{searchPhrase}")]
        public async Task<IActionResult> Search(string searchPhrase)
        {
            List<ProductDto> producDtos = await productService.Search(searchPhrase);
            return View(producDtos);
        }

    }
}

RestaurantMVC/RestaurantMVC/Views/Order/Addproduct.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<ProductDto>   
<table class="content-wrapper table table-dark">
    <tr>
        <th scope="col">
            @Html.DisplayName("Name")
        </th>
        <th scope="col">
            @Html.DisplayName("Price")
        </th>
    </tr>
    @foreach (var dto in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => dto.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => dto.Price)
            </td>
            <td>
                @using (Html.BeginForm("AddProduct", "Order", 
                new { 
                    orderId = ViewContext.RouteData.Values["orderId"], 
                    productId = dto.Id 
                },
                FormMethod.Post))
                {
                    <input type="submit" class="button" value="Add" />
                }
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Go back", "Index", "Order")

RestaurantMVC/RestaurantMVC/Views/Order/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

RestaurantMVC/RestaurantMVC/Views/Order/Get.cshtml
@using Microsoft.AspNetCore.Routing
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- wypisywanie wszystkich zamowien i ich tworzenie -->
@model List<OrderDto>
<table class="content-wrapper table table-dark">
    <tr>
        <th scope="col">
            @Html.DisplayName("ID")
        </th>
        <th scope="col">
            @Html.DisplayName("Is done?")
        </th>
        <th scope="col">
            @Html.DisplayName("User")
        </th>
        <th></th>
    </tr>
    @foreach (OrderDto dto in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => dto.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => dto.isDone)
            </td>
             <td>
                @Html.DisplayFor(modelItem => dto.User.Username)
            </td>
            <td>
                @Html.ActionLink("Add Products", "AddProduct", "Order", new { id = dto.Id })
            </td>
            <td>
                @Html.ActionLink("Products", "products", "Order", new { id = dto.Id })
            </td>
            <td>
                @using (Html.BeginForm("Delete", "Order", new { id = dto.Id }))
                {
                    <input class="btn btn-outline-danger" type="submit" value="Delete Item" />
                }
            </td>
        </tr>
    }
</table>
@using (Html.BeginForm("Create", "Order", FormMethod.Post))
{
    <input type="submit" class="button" value="Create new order" />
}

RestaurantMVC/RestaurantMVC/Views/Order/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

RestaurantMVC/RestaurantMVC/Views/Order/Products.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model IEnumerable<ProductDto>



<table class="content-wrapper table table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>

            </td>
        </tr>
}
    </tbody>
    <tfoot>
        <tr>
            <th>
                Total cost:
            </th>
            <th>
                @Decimal.Parse(Model.Sum(x => x.Price).ToString("0.00"))
            </th>
            <th></th>
        </tr>
    </tfoot>
</table>

@Html.ActionLink("Go back", "Index", "Order")

@{

}